---
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches-ignore: 
      - 'main'
      - 'master'

jobs:
  do_it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
