---
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: 
      - '*'
      - '*/*'
      - '**'    
      - '!main'
      - '!master'

jobs:
  do_it:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
